// TODO: automatically generate this file using cmake

#include "BaseLocationImpl.cpp"
#include "BWTA.cpp"
#include "BWTA_Result.cpp"
#include "calculate_connectivity.cpp"
#include "ChokepointImpl.cpp"
#include "ConnectedComponent.cpp"
#include "extract_polygons.cpp"
#include "find_base_locations.cpp"
#include "get_voronoi_edges.cpp"
#include "Graph.cpp"
#include "load_data.cpp"
#include "Node.cpp"
#include "pathfinding.cpp"
#include "Polygon.cpp"
#include "RegionImpl.cpp"
#include "terrain_analysis.cpp"
#include "util.cpp"
#include "VertexData.cpp"
